#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libpcap
Version  : 1.8.1
Release  : 16
URL      : http://www.tcpdump.org/release/libpcap-1.8.1.tar.gz
Source0  : http://www.tcpdump.org/release/libpcap-1.8.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libpcap-bin
Requires: libpcap-lib
Requires: libpcap-doc
BuildRequires : bison
BuildRequires : cmake
BuildRequires : dbus-dev
BuildRequires : flex
BuildRequires : libnl-dev

%description
LIBPCAP 1.x.y
www.tcpdump.org
Please send inquiries/comments/reports to:
tcpdump-workers@lists.tcpdump.org

%package bin
Summary: bin components for the libpcap package.
Group: Binaries

%description bin
bin components for the libpcap package.


%package dev
Summary: dev components for the libpcap package.
Group: Development
Requires: libpcap-lib
Requires: libpcap-bin
Provides: libpcap-devel

%description dev
dev components for the libpcap package.


%package doc
Summary: doc components for the libpcap package.
Group: Documentation

%description doc
doc components for the libpcap package.


%package lib
Summary: lib components for the libpcap package.
Group: Libraries

%description lib
lib components for the libpcap package.


%prep
%setup -q -n libpcap-1.8.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pcap-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/pcap/bluetooth.h
/usr/include/pcap/bpf.h
/usr/include/pcap/can_socketcan.h
/usr/include/pcap/dlt.h
/usr/include/pcap/export-defs.h
/usr/include/pcap/ipnet.h
/usr/include/pcap/namedb.h
/usr/include/pcap/nflog.h
/usr/include/pcap/pcap.h
/usr/include/pcap/sll.h
/usr/include/pcap/usb.h
/usr/include/pcap/vlan.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man7/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
