#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE089DEF1D9C15D0D (release@tcpdump.org)
#
Name     : libpcap
Version  : 1.9.0
Release  : 21
URL      : http://www.tcpdump.org/release/libpcap-1.9.0.tar.gz
Source0  : http://www.tcpdump.org/release/libpcap-1.9.0.tar.gz
Source99 : http://www.tcpdump.org/release/libpcap-1.9.0.tar.gz.sig
Summary  : Platform-independent network traffic capture library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libpcap-bin
Requires: libpcap-lib
Requires: libpcap-license
Requires: libpcap-man
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : dbus-dev
BuildRequires : flex
BuildRequires : glibc-dev
BuildRequires : libnl-dev
BuildRequires : pkgconfig(dbus-1)

%description
To report a security issue please send an e-mail to security@tcpdump.org.
To report bugs and other problems, contribute patches, request a
feature, provide generic feedback etc please see the file
[CONTRIBUTING](CONTRIBUTING.md) in the libpcap source tree root.

%package bin
Summary: bin components for the libpcap package.
Group: Binaries
Requires: libpcap-license
Requires: libpcap-man

%description bin
bin components for the libpcap package.


%package dev
Summary: dev components for the libpcap package.
Group: Development
Requires: libpcap-lib
Requires: libpcap-bin
Provides: libpcap-devel

%description dev
dev components for the libpcap package.


%package lib
Summary: lib components for the libpcap package.
Group: Libraries
Requires: libpcap-license

%description lib
lib components for the libpcap package.


%package license
Summary: license components for the libpcap package.
Group: Default

%description license
license components for the libpcap package.


%package man
Summary: man components for the libpcap package.
Group: Default

%description man
man components for the libpcap package.


%prep
%setup -q -n libpcap-1.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536133223
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1536133223
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libpcap
cp LICENSE %{buildroot}/usr/share/doc/libpcap/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pcap-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/pcap/bluetooth.h
/usr/include/pcap/bpf.h
/usr/include/pcap/can_socketcan.h
/usr/include/pcap/compiler-tests.h
/usr/include/pcap/dlt.h
/usr/include/pcap/funcattrs.h
/usr/include/pcap/ipnet.h
/usr/include/pcap/namedb.h
/usr/include/pcap/nflog.h
/usr/include/pcap/pcap-inttypes.h
/usr/include/pcap/pcap.h
/usr/include/pcap/sll.h
/usr/include/pcap/usb.h
/usr/include/pcap/vlan.h
/usr/lib64/libpcap.so
/usr/lib64/pkgconfig/libpcap.pc
/usr/share/man/man3/pcap.3pcap
/usr/share/man/man3/pcap_activate.3pcap
/usr/share/man/man3/pcap_breakloop.3pcap
/usr/share/man/man3/pcap_can_set_rfmon.3pcap
/usr/share/man/man3/pcap_close.3pcap
/usr/share/man/man3/pcap_compile.3pcap
/usr/share/man/man3/pcap_create.3pcap
/usr/share/man/man3/pcap_datalink.3pcap
/usr/share/man/man3/pcap_datalink_name_to_val.3pcap
/usr/share/man/man3/pcap_datalink_val_to_description.3pcap
/usr/share/man/man3/pcap_datalink_val_to_name.3pcap
/usr/share/man/man3/pcap_dispatch.3pcap
/usr/share/man/man3/pcap_dump.3pcap
/usr/share/man/man3/pcap_dump_close.3pcap
/usr/share/man/man3/pcap_dump_file.3pcap
/usr/share/man/man3/pcap_dump_flush.3pcap
/usr/share/man/man3/pcap_dump_fopen.3pcap
/usr/share/man/man3/pcap_dump_ftell.3pcap
/usr/share/man/man3/pcap_dump_open.3pcap
/usr/share/man/man3/pcap_file.3pcap
/usr/share/man/man3/pcap_fileno.3pcap
/usr/share/man/man3/pcap_findalldevs.3pcap
/usr/share/man/man3/pcap_fopen_offline.3pcap
/usr/share/man/man3/pcap_fopen_offline_with_tstamp_precision.3pcap
/usr/share/man/man3/pcap_free_datalinks.3pcap
/usr/share/man/man3/pcap_free_tstamp_types.3pcap
/usr/share/man/man3/pcap_freealldevs.3pcap
/usr/share/man/man3/pcap_freecode.3pcap
/usr/share/man/man3/pcap_get_required_select_timeout.3pcap
/usr/share/man/man3/pcap_get_selectable_fd.3pcap
/usr/share/man/man3/pcap_get_tstamp_precision.3pcap
/usr/share/man/man3/pcap_geterr.3pcap
/usr/share/man/man3/pcap_getnonblock.3pcap
/usr/share/man/man3/pcap_inject.3pcap
/usr/share/man/man3/pcap_is_swapped.3pcap
/usr/share/man/man3/pcap_lib_version.3pcap
/usr/share/man/man3/pcap_list_datalinks.3pcap
/usr/share/man/man3/pcap_list_tstamp_types.3pcap
/usr/share/man/man3/pcap_lookupdev.3pcap
/usr/share/man/man3/pcap_lookupnet.3pcap
/usr/share/man/man3/pcap_loop.3pcap
/usr/share/man/man3/pcap_major_version.3pcap
/usr/share/man/man3/pcap_minor_version.3pcap
/usr/share/man/man3/pcap_next.3pcap
/usr/share/man/man3/pcap_next_ex.3pcap
/usr/share/man/man3/pcap_offline_filter.3pcap
/usr/share/man/man3/pcap_open_dead.3pcap
/usr/share/man/man3/pcap_open_dead_with_tstamp_precision.3pcap
/usr/share/man/man3/pcap_open_live.3pcap
/usr/share/man/man3/pcap_open_offline.3pcap
/usr/share/man/man3/pcap_open_offline_with_tstamp_precision.3pcap
/usr/share/man/man3/pcap_perror.3pcap
/usr/share/man/man3/pcap_sendpacket.3pcap
/usr/share/man/man3/pcap_set_buffer_size.3pcap
/usr/share/man/man3/pcap_set_datalink.3pcap
/usr/share/man/man3/pcap_set_immediate_mode.3pcap
/usr/share/man/man3/pcap_set_promisc.3pcap
/usr/share/man/man3/pcap_set_protocol_linux.3pcap
/usr/share/man/man3/pcap_set_rfmon.3pcap
/usr/share/man/man3/pcap_set_snaplen.3pcap
/usr/share/man/man3/pcap_set_timeout.3pcap
/usr/share/man/man3/pcap_set_tstamp_precision.3pcap
/usr/share/man/man3/pcap_set_tstamp_type.3pcap
/usr/share/man/man3/pcap_setdirection.3pcap
/usr/share/man/man3/pcap_setfilter.3pcap
/usr/share/man/man3/pcap_setnonblock.3pcap
/usr/share/man/man3/pcap_snapshot.3pcap
/usr/share/man/man3/pcap_stats.3pcap
/usr/share/man/man3/pcap_statustostr.3pcap
/usr/share/man/man3/pcap_strerror.3pcap
/usr/share/man/man3/pcap_tstamp_type_name_to_val.3pcap
/usr/share/man/man3/pcap_tstamp_type_val_to_description.3pcap
/usr/share/man/man3/pcap_tstamp_type_val_to_name.3pcap

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpcap.so.1
/usr/lib64/libpcap.so.1.9.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libpcap/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/pcap-config.1
/usr/share/man/man5/pcap-savefile.5
/usr/share/man/man7/pcap-filter.7
/usr/share/man/man7/pcap-linktype.7
/usr/share/man/man7/pcap-tstamp.7
